### ISSUE TITLE
For branch master change version of dependency bugsnag in composer.json

### ISSUE THREAD

**Issue by rud-felix** [evolution7/Evolution7BugsnagBundle#21]
We need some fix from **bugsnag/bugsnag-php** but can't take it because in your **composer.json** dependency version is **"2.*"**. 
Can you change it to **"dev-master"** for branch **master** than we can use dev version of **bugsnag/bugsnag-php**

**Comment by thoaionline** [comment]
@rud-felix if there are new fixes in bugsnag-php, they'll need to make a release. Alternatively, you can set up a `branch-alias` as instructed here: https://getcomposer.org/doc/articles/aliases.md#branch-alias

Having a `dev-master` dependency in a stable+public repo is probably not a good idea.
